### ISSUE TITLE
Recompiling resources only fails

### ISSUE THREAD

**Issue by ABritishPerson** [dongfangxunlei/apktool5#4]
When I recompile an apk, everything works perfectly, however if I decompile resources then try to recompile it, I get this error
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 117, --version-name, 8.5.0.1164, -F, /data/data/per.pqy.apktool/APKTOOL4919982352690053629.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Documents/blue_src/res, -M, /sdcard/Documents/blue_src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	at brut.androlib.Androlib.buildResources(Androlib.java:396)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 117, --version-name, 8.5.0.1164, -F, /data/data/per.pqy.apktool/APKTOOL4919982352690053629.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Documents/blue_src/res, -M, /sdcard/Documents/blue_src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 117, --version-name, 8.5.0.1164, -F, /data/data/per.pqy.apktool/APKTOOL4919982352690053629.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Documents/blue_src/res, -M, /sdcard/Documents/blue_src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:93)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:485)
	at brut.util.OS.exec(OS.java:84)
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 10 more
I: Using Apktool 2.0.0-07ea41-SNAPSHOT
I: Copying /sdcard/Documents/blue_src classes.dex file...
I: Building resources...

I'll be honest, I don't exactly know what that means but I was hoping somebody could help?

**Comment by dongfangxunlei** [comment]
Yes,some samsung phone has this problem.You can use 5.1.1 instead.

**Comment by ABritishPerson** [comment]
Damn, I was enjoying the speed of 5.2.0. I guess Lollipop messed everything up :/ Thanks for the reply

**Comment by ABritishPerson** [comment]
Sorry to come back to this but I just wanted to ask if there's a possibility for a fix for this in the future? 
Just because if there isn't I'm going to consider going back to Android KitKat

**Comment by dongfangxunlei** [comment]
It is the problem of selinux, not android version.I don't think kitkat would work.

**Comment by ABritishPerson** [comment]
Ah okay, thanks a lot for your help. 5.1.1 didn't work either but 5.1.0 is great
